# This is a basic workflow to help you get started with Actions

name: build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build
        uses: stephenhu/static-action@v1
      - name: checkout destination
        uses: actions/checkout@v2
        with:
          repository: stephenhu/stephenhu.github.io
          path: www
          ref: main
          token: ${{ secrets.TOKEN_GITHUB }}
      - name: copy static files
        run: |
          cp index.html www
          cp css/stephenhu3.css www/css/stephenhu3.css
          cp js/stephenhu.js www/js/stephenhu.js
      - name: Commit updated file
        run: |
          cd www
          git config --local user.email "github-actions@users.noreply.github.com"
          git config --local user.name "github-actions"
          git add index.html
          git commit -m "Update page" -a
          git push
